# Reference: https://skamalakannan.dev/posts/dockerizing-your-spa/

FROM nginx:alpine

# We're only copying here because we assume that the client has been built outside of docker
# This decision is mostly for GitHub actions. By building outside of Docker, we're able to use
# the yarn cache of GH actions
COPY client/dist /usr/share/nginx/html
COPY client/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

STOPSIGNAL SIGTERM

CMD ["nginx", "-g", "daemon off;"]
