FROM node:20-alpine

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY server/package.json .
# The server package doesn't have its own yarn.lock file, so we need to use  the one present at the monorepo's root
COPY yarn.lock .
RUN yarn install

COPY server/src ./src
COPY server/.env .
COPY server/tsconfig.json .
RUN yarn build

RUN chown -R node:node /home/node/app
USER node

EXPOSE 3000
ENTRYPOINT ["node", "dist/index.js"]
