name: To Develop

on:
  push:
    branches:
      - develop-**
  pull_request:
    branches:
      - develop-**

jobs:
  static-check-client:
    uses: ./.github/workflows/static-check-client-reusable.yml
  static-check-server:
    uses: ./.github/workflows/static-check-server-reusable.yml
  test:
    needs:
      - static-check-client
      - static-check-server
    uses: ./.github/workflows/test-reusable.yml
  build:
    needs:
      - test
    uses: ./.github/workflows/build-reusable.yml
    with:
      docker-push: ${{ github.event_name == 'push' }}
      tag-prepend: develop
