name: To Develop

on:
  push:
    branches:
      - develop-**
  pull_request:
    branches:
      - develop-**

jobs:
  verify-client:
    uses: ./.github/workflows/verify-client-reusable.yml
  verify-server:
    uses: ./.github/workflows/verify-server-reusable.yml
  verify:
    needs:
      - verify-client
      - verify-server
    uses: ./.github/workflows/verify-reusable.yml
  build:
    needs:
      - verify
    uses: ./.github/workflows/build-reusable.yml
    with:
      docker-push: ${{ github.event_name == 'push' }}
      tag-prepend: develop-
