name: On Push

on:
  push:
    branches-ignore:
      - develop-*

jobs:
  static-check-client:
    uses: ./.github/workflows/static-check-client-reusable.yml
  static-check-server:
    uses: ./.github/workflows/static-check-server-reusable.yml
  test:
    needs:
      - static-check-client
      - static-check-server
    uses: ./.github/workflows/test-reusable.yml
