name: Common -- run tests

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install client dependencies
        run: yarn install
        working-directory: ./client
        shell: bash

      - name: Install server dependencies
        run: yarn install
        working-directory: ./server
        shell: bash
      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./client
          build: yarn build
          start: yarn preview, cd ../server && yarn dev
          wait-on: http://localhost:4173, http://localhost:3000
          config: baseUrl=http://localhost:4173
