name: Common -- run tests

on:
  workflow_call:

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: yarn

      - name: Install client dependencies
        run: yarn install
        working-directory: ./client
        shell: bash

      - name: Install server dependencies
        run: yarn install
        working-directory: ./server
        shell: bash

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install: false
          working-directory: ./client
          build: yarn build
          start: yarn preview, yarn test:e2e:server
          wait-on: http://localhost:4173, http://localhost:3000
          config: baseUrl=http://localhost:4173

      - name: Create screenshot artifacts due to failure
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: ./client/cypress/screenshots
